### ISSUE TITLE
Create LICENSE file

### ISSUE THREAD

**Issue by jaredsmith** [isaacs/isexe#1]
Will you please create a LICENSE file with the copyright information and the text of the ISC license?  The ISC license specifically states that the license text much accompany the source code.

**Comment by avindra** [comment]
Looks like this is done :+1:

**Comment by shinnn** [comment]
Yes, fixed in https://github.com/isaacs/isexe/commit/68f5be68613e7ce90fc9d11bf3aab158747749db.
